version: "3.9"

services:
  db:
    image: postgres:15
    container_name: collisions_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collisions
    ports:
      - "5433:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d collisions"]
      interval: 5s
      timeout: 5s
      retries: 15

  ingest:
    build: .
    container_name: collisions_ingest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgresql+psycopg2://postgres:postgres@db:5432/collisions
      CSV_FILE: motor_vehicle_collisions_2023_2024.csv
    command: ["python", "ingest_data.py"]
    volumes:
      - .:/app
    restart: "no"

  app:
    build: .
    container_name: collisions_app
    depends_on:
      - db
    environment:
      DB_URL: postgresql+psycopg2://postgres:postgres@db:5432/collisions
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501

volumes:
  postgres_data:
